version: '3.8'

services:
  fastapi-ml:
    build:
      context: .
      dockerfile: Dockerfile
    # image: nasfong/machine-learning:latest
    container_name: ml-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://admin:your_mongo_password@mongodb.nasfong.site:443/motor?ssl=true&authSource=admin
    volumes:
      # Mount entire source for hot reload
      - .:/app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
