version: '3.8'

services:
  fastapi-ml:
    build:
      context: .
      dockerfile: Dockerfile
    # image: nasfong/machine-learning:latest
    container_name: ml-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://admin:your_mongo_password@mongodb.nasfong.site:443/motor?ssl=true&authSource=admin
      # Remove https:// from MINIO_ENDPOINT - just use hostname:port
      - MINIO_ENDPOINT=minio-api.nasfong.site
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=Rening007minio
      # Set to true since you're using HTTPS endpoint
      - MINIO_SECURE=true
    volumes:
      # Mount entire source for hot reload
      - .:/app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload